# Generated by Django 2.0 on 2018-07-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200, null=True)),
                ('plan', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('None', 'None')], max_length=25, null=True)),
                ('occupancy', models.CharField(blank=True, choices=[('Owner_Staying', 'Owner_Staying'), ('Tenant_Staying', 'Tenant_Staying'), ('Vacant', 'Vacant')], max_length=25, null=True)),
                ('bed_count', models.IntegerField(blank=True, null=True)),
                ('furnish', models.CharField(blank=True, choices=[('Fully furnished', 'Fully furnished'), ('Semi furnished', 'Semi furnished'), ('Unfurnished', 'Unfurnished')], max_length=25, null=True)),
                ('tenant_tyoe', models.CharField(blank=True, choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Family', 'Family'), ('Any', 'Any')], max_length=25, null=True)),
                ('house_type', models.CharField(blank=True, choices=[('Apartment', 'Apartment'), ('Independnet', 'Independnet'), ('Villa', 'Villa')], max_length=25, null=True)),
                ('current_rent', models.IntegerField(blank=True, null=True)),
                ('expected_rent', models.IntegerField(blank=True, null=True)),
                ('current_secuirity_deposit', models.IntegerField(blank=True, null=True)),
                ('expected_secuirity_deposit', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
