# Generated by Django 2.0.7 on 2018-07-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormSubmition',
            new_name='FormSubmission',
        ),
    ]
