# Generated by Django 2.0.7 on 2018-07-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0002_auto_20180716_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmission',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='industryrelation',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='message',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='professionfield',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='queryabout',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='subject',
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='bed_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='current_deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='current_rent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='expected_deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='expected_rent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='furnish',
            field=models.CharField(blank=True, choices=[('Fully furnished', 'Fully furnished'), ('Semi furnished', 'Semi furnished'), ('Unfurnished', 'Unfurnished')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='house_type',
            field=models.CharField(blank=True, choices=[('Apartment', 'Apartment'), ('Independnet', 'Independnet'), ('Villa', 'Villa')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='occupancy',
            field=models.CharField(blank=True, choices=[('Staying', 'Staying'), ('Vacant', 'Vacant')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='plan',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('None', 'None')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='tenants',
            field=models.CharField(blank=True, choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Family', 'Family'), ('Any', 'Any')], max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='IndustryType',
        ),
        migrations.DeleteModel(
            name='ProfessionField',
        ),
        migrations.DeleteModel(
            name='QueryType',
        ),
    ]
