# Generated by Django 2.0.7 on 2018-07-20 06:44

import Homes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Apartment', 'Apartment'), ('Independnet', 'Independnet'), ('Villa', 'Villa')], max_length=25, null=True)),
                ('rent', models.CharField(blank=True, max_length=10, null=True)),
                ('deposit', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('accomodation_allowed', models.CharField(blank=True, choices=[('Girls', 'Girls'), ('Boys', 'Boys'), ('Family', 'Family')], max_length=25, null=True)),
                ('accomodation_type', models.CharField(blank=True, choices=[('Shared room', 'Shared room'), ('Private room', 'Private room'), ('Entire house', 'Entire house')], max_length=25, null=True)),
                ('accoomodation_count', models.IntegerField(blank=True, null=True)),
                ('available_count', models.IntegerField(blank=True, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('rules', models.CharField(blank=True, max_length=500, null=True)),
                ('amenity', models.ManyToManyField(related_name='house_amenities', to='Homes.Amenity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HousePictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to=Homes.models.get_picture_upload_path)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Homes.House')),
            ],
        ),
        migrations.CreateModel(
            name='HouseVisits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('code', models.CharField(max_length=10)),
                ('is_visited', models.BooleanField(default=False)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='visit_house', to='Homes.House')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubAmenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pic', models.ImageField(blank=True, null=True, upload_to=Homes.models.get_amenity_picture_upload_path)),
            ],
        ),
        migrations.AddField(
            model_name='amenity',
            name='sub_amenity',
            field=models.ManyToManyField(related_name='house_sub_amenity', to='Homes.SubAmenity'),
        ),
    ]
