# Generated by Django 2.0.7 on 2018-07-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='category',
            field=models.CharField(blank=True, choices=[('Inhouse', 'Inhouse'), ('Society', 'Society')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='furnish_type',
            field=models.CharField(blank=True, choices=[('Fully furnished', 'Fully furnished'), ('Semi furnished', 'Semi furnished'), ('Unfurnished', 'Unfurnished')], max_length=25, null=True),
        ),
    ]
