# Generated by Django 2.0 on 2018-07-24 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='houseamenity',
            options={'verbose_name_plural': 'House Amenities'},
        ),
        migrations.AlterModelOptions(
            name='subamenity',
            options={'verbose_name_plural': 'Sub Amenities'},
        ),
        migrations.AddField(
            model_name='sharedroom',
            name='accomodation_type',
            field=models.CharField(blank=True, choices=[('shared', 'Shared rooms'), ('private', 'Private rooms'), ('flat', 'Entire house')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='sharedroom',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sharedroom', to='Homes.House'),
        ),
    ]
