# Generated by Django 2.0 on 2018-07-24 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0002_auto_20180724_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('rent', models.FloatField()),
                ('deposit', models.FloatField()),
                ('available', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spaces', to='Homes.House')),
            ],
        ),
        migrations.RemoveField(
            model_name='flat',
            name='available',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='flat_no',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='house',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='visible',
        ),
        migrations.RemoveField(
            model_name='privateroom',
            name='available',
        ),
        migrations.RemoveField(
            model_name='privateroom',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='privateroom',
            name='house',
        ),
        migrations.RemoveField(
            model_name='privateroom',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='privateroom',
            name='room_no',
        ),
        migrations.RemoveField(
            model_name='privateroom',
            name='visible',
        ),
        migrations.RemoveField(
            model_name='sharedroom',
            name='accomodation_type',
        ),
        migrations.RemoveField(
            model_name='sharedroom',
            name='available',
        ),
        migrations.RemoveField(
            model_name='sharedroom',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='sharedroom',
            name='house',
        ),
        migrations.RemoveField(
            model_name='sharedroom',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='sharedroom',
            name='room_no',
        ),
        migrations.RemoveField(
            model_name='sharedroom',
            name='visible',
        ),
        migrations.AddField(
            model_name='flat',
            name='space',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flat', to='Homes.Space'),
        ),
        migrations.AddField(
            model_name='privateroom',
            name='space',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='private_room', to='Homes.Space'),
        ),
        migrations.AddField(
            model_name='sharedroom',
            name='space',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shared_room', to='Homes.Space'),
        ),
    ]
