# Generated by Django 2.0 on 2018-07-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0003_auto_20180724_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='type',
            field=models.CharField(choices=[('shared', 'Shared rooms'), ('private', 'Private rooms'), ('flat', 'Entire house')], default='flat', max_length=20),
            preserve_default=False,
        ),
    ]
