# Generated by Django 2.0 on 2018-07-24 19:23

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0004_space_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyexpensecategory',
            options={'verbose_name_plural': 'Monthly expense categories`'},
        ),
        migrations.AddField(
            model_name='sharedroom',
            name='bed_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='house',
            name='accomodation_allowed',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('girls', 'Girls'), ('boys', 'Boys'), ('family', 'Family')], max_length=25),
        ),
        migrations.AlterField(
            model_name='house',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='furnish_type',
            field=models.CharField(blank=True, choices=[('full', 'Fully furnished'), ('semi', 'Semi furnished'), ('nil', 'Unfurnished')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('independent', 'Independent'), ('villa', 'Villa')], max_length=25, null=True),
        ),
    ]
